//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK.Template.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeSnippetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeSnippetResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GK.Template.Resources.CodeSnippetResources", typeof(CodeSnippetResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{7}
        ///
        ///namespace generated
        ///{{
        ///
        ///{10}
        ///
        ///{8}
        ///
        ///{4}public class {0}
        ///{4}{{
        ///
        ///{9}
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///{4}{4}public {3}()
        ///{4}{4}{{
        ///{4}{4}{4}// Constructor logic here.
        ///{4}{4}}}
        ///
        ///{5}
        ///
        ///{11}
        ///
        ///{4}{4}public override string ToString()
        ///{4}{4}{{
        ///{4}{4}{4}{6}
        ///{4}{4}}}
        ///{4}}}
        ///
        ///}}
        ///.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////// &lt;summary&gt;
        ////// {0}
        ////// &lt;/summary&gt;.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{3}{3}public {0}({1})
        ///{3}{3}{{
        ///{2}
        ///{3}{3}}}
        ///.
        /// </summary>
        internal static string Constructor {
            get {
                return ResourceManager.GetString("Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return base.ToString();.
        /// </summary>
        internal static string DefaultToString {
            get {
                return ResourceManager.GetString("DefaultToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class {0}EventArgs : EventArgs
        ///{{
        ///
        ///{1}
        ///
        ///    public {0}EventArgs()
        ///    {{
        ///        // Constructor logic here
        ///    }}
        ///}}
        ///.
        /// </summary>
        internal static string EventArgClass {
            get {
                return ResourceManager.GetString("EventArgClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tpublic {0} {1} {{ get; set; }}\r\n.
        /// </summary>
        internal static string EventArgProperty {
            get {
                return ResourceManager.GetString("EventArgProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public delegate void {0}EventHandler(object sender, {0}EventArgs e);
        ///.
        /// </summary>
        internal static string EventDelegate {
            get {
                return ResourceManager.GetString("EventDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public delegate void {0}EventHandler(object sender, EventArgs e);
        ///.
        /// </summary>
        internal static string EventDelegateDefault {
            get {
                return ResourceManager.GetString("EventDelegateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private {0} {1} = {3};.
        /// </summary>
        internal static string PrivateMember {
            get {
                return ResourceManager.GetString("PrivateMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private {0} {1};.
        /// </summary>
        internal static string PrivateMemberNoDefault {
            get {
                return ResourceManager.GetString("PrivateMemberNoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private static {0} {1} = {3};.
        /// </summary>
        internal static string PrivateStaticMember {
            get {
                return ResourceManager.GetString("PrivateStaticMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private static {0} {1};.
        /// </summary>
        internal static string PrivateStaticMemberNoDefault {
            get {
                return ResourceManager.GetString("PrivateStaticMemberNoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{5}
        ///
        ///{8}
        ///{7}
        ///{3} {0} {2}
        ///{{
        ///{4}get
        ///{4}{{
        ///{4}{4}return {1};
        ///{4}}}
        ///{4}set
        ///{4}{{
        ///{4}{4}{1} = value;
        ///{4}}}
        ///}}
        ///
        ///{6}.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{5}
        ///
        ///{8}
        ///{7}
        ///{3} {0} {2}
        ///{{
        ///{4}get
        ///{4}{{
        ///{4}{4}return {1};
        ///{4}}}
        ///}}
        ///
        ///{6}.
        /// </summary>
        internal static string PropertyGetOnly {
            get {
                return ResourceManager.GetString("PropertyGetOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{5}
        ///
        ///{8}
        ///{7}
        ///{3} {0} {2} {{ get; set; }}
        ///
        ///{6}.
        /// </summary>
        internal static string PropertyShort {
            get {
                return ResourceManager.GetString("PropertyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public event EventHandler&lt;{0}EventArgs&gt; {0} = delegate {{ }};.
        /// </summary>
        internal static string PublicEvent {
            get {
                return ResourceManager.GetString("PublicEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public event EventHandler&lt;{0}EventArgs&gt; {0} = delegate {{ }};
        ///.
        /// </summary>
        internal static string PublicEventDefault {
            get {
                return ResourceManager.GetString("PublicEventDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public event EventHandler&lt;{0}EventArgs&gt; {0} = delegate {{ }};.
        /// </summary>
        internal static string PublicEventNoDelegate {
            get {
                return ResourceManager.GetString("PublicEventNoDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private void raiseEvent{0} ({1})
        ///{{
        ///    EventHandler&lt;{0}EventArgs&gt; handler = {0};
        ///    if (handler != null)
        ///    {{
        ///        {0}EventArgs ea = new {0}EventArgs();
        ///{2}
        ///        handler(this, ea);
        ///    }}
        ///}}
        ///.
        /// </summary>
        internal static string RaiseEventMethod {
            get {
                return ResourceManager.GetString("RaiseEventMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private void raiseEvent{0} ({1})
        ///{{
        ///    EventHandler&lt;{0}EventArgs&gt; handler = {0};
        ///    if (handler != null)
        ///    {{
        ///        {0}EventArgs ea = new {0}EventArgs();
        ///{2}
        ///        handler(this, ea);
        ///    }}
        ///}}.
        /// </summary>
        internal static string RaiseEventMethodDefault {
            get {
                return ResourceManager.GetString("RaiseEventMethodDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private void raiseEvent{0} ({1})
        ///{{
        ///    {0}EventHandler handler = {0};
        ///    if (handler != null)
        ///    {{
        ///        EventArgs ea = new EventArgs();
        ///        handler(this, ea);
        ///    }}
        ///}}.
        /// </summary>
        internal static string RaiseEventMethodNoDelegate {
            get {
                return ResourceManager.GetString("RaiseEventMethodNoDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1},.
        /// </summary>
        internal static string RaiseEventParameter {
            get {
                return ResourceManager.GetString("RaiseEventParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t\tea.{0} = {1};\r\n.
        /// </summary>
        internal static string RaiseEventParameterAssignment {
            get {
                return ResourceManager.GetString("RaiseEventParameterAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using {0};
        ///    .
        /// </summary>
        internal static string UsingLine {
            get {
                return ResourceManager.GetString("UsingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [XmlElement(&quot;{0}&quot;, typeof({1}))].
        /// </summary>
        internal static string XmlElement {
            get {
                return ResourceManager.GetString("XmlElement", resourceCulture);
            }
        }
    }
}
