//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK.Template.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RandomResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RandomResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GK.Template.Resources.RandomResources", typeof(RandomResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waardh,Waarder,Waardenburg,Waarde,Waalwijk,Waalre,Waal,Vuren,Vuile Riete,Vught,Vrouwenpolder,Vrouwenparochie,Vrouwenakker,Vroomshoop,Vrijhoevecapelle,Vriezenveensewijk,Vriezenveen,Vriescheloo,Vries,Vreeswijk,Vreeland,Vredepeel,Vredenheim,Vragender,Vortummullem,Vorstenbosch,Vorden,Vorchten,Voorthuizen,Voorstonden,Voorst,Voorst,Voorschoten,Voorhout,Voorburg,Vondelingenplaat (RT),Vondelingenplaat ,Volthe,Vollenhove,Volkel,Volendam,Vogelwaarde,Vogelenzang,Voerendaal,Vlodrop,Vlist,Vlissingen,Vlierden,Vlieland,Vl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CityNames {
            get {
                return ResourceManager.GetString("CityNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,Aachje,Aacht,Aachte,Aachtje,Aachtsje,Aad,Aadi,Aadje,Aaf,Aaffina,Aafi,Aafien,Aafina,Aafje,Aafke,Aafkelina,Aafkeline,Aafkje,Aafko,Aafra,Aaftien,Aag,Aagje,Aagjen,Aagt,Aagte,Aagtje,Aai,Aaie,Aaielt,Aaike,Aaildert,Aailert,Aailt,Aaiolt,Aaite,Aaize,Aakje,Aal,Aalbert,Aalberta,Aalbertina,Aalbertje,Aalbertus,Aalbrecht,Aalbrechta,Aalbrechtje,Aalderd,Aalderik,Aalderika,Aalderikje,Aalderikus,Aalderk,Aaldert,Aaldertje,Aaldertsje,Aaldrik,Aaldrika,Aaldrikje,Aale,Aalf,Aalheit,Aaliyah,Aalje,Aalk,Aalke,Aalmoed,Aalmoet,Aalrik, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstNames {
            get {
                return ResourceManager.GetString("FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aalts,Aarden,Aarts,Adelaar,Adriaansen,Adriaensdr,Adriaense,Adryaens,Aeije,Aelftrud van Wessex,Aertsz (Heerschop),Alenburg, van,Allemanië, van,Allemannië, van,Alpaidis,Amalrada,Amstel, van,Ansems,Appelman,Arens,Arent,Ariens (Kapteijn),Ariens Ansems,Arkel, van,Arnold,Arnsberg, van,Arts,Aschman,Assem, van den,Asten, van,Avoirt, van der,Baalen, van,Backer,Backer, de,Barents,Bartels,Bastiaanse,Bastiaense,Bave,Beaumont &quot;de Oude&quot;, van,Beaumont, van,Becht,Beeck Beeckmans, van,Beeck, van,Beek, van,Beekman,Beer, de,B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
    }
}
